#ifndef STAGE_CONTROL_CONFIG_H__
#define STAGE_CONTROL_CONFIG_H__

typedef enum {
	NONE = 0,
	BRICK_NORMAL,
	BRICK_COIN,
	HATENA_MUSH_PW,
	HATENA_MUSH_1UP,
	HATENA_STAR,
	HATENA_COIN,
	HATENA_LVY,
	ZHUGE_LIANG,
	FLOOR,
	EARTHEN_PIPE_FL,
	EARTHEN_PIPE_FR,
	EARTHEN_PIPE_RL,
	EARTHEN_PIPE_RR,
	STAIRS,
	BLOCK_MAX
}E_BlockType;

#endif